# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main", "DeveloperBranch", "se05-MVC" ]
  pull_request:
    branches: [ "main", "DeveloperBranch" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: compile
      run: sbt compile
    - name: Run tests
      run: sbt test

  run_tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Build Project and export Coverage
       env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
       run: |
         export CI_BRANCH="${GITHUB_REF#refs/heads/}"
         sbt clean jacoco jacocoCoveralls

